/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.cadastros;

import com.mycompany.build.AtendimentoBuild;
import com.mycompany.casouso.AtendimentoUC;
import com.mycompany.casouso.ClienteUC;
import com.mycompany.casouso.FuncionarioUC;
import com.mycompany.casouso.VeiculoUC;
import com.mycompany.models.Atendimento;
import com.mycompany.models.Cliente;
import com.mycompany.models.Funcionario;
import com.mycompany.models.Veiculo;
import com.mycompany.virtuais.EntidadesVirtuais;
import com.mycompany.virtuais.PainelCadastros;
import com.mycompany.virtuais.UC;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


/**
 *
 * @author ribei
 */
public class PainelCadastroAtendimento extends PainelCadastros  {

    /**
     * Creates new form PainelCadastroAtendimento
     */
    public PainelCadastroAtendimento() {
        initComponents();
        VeiculoUC vuc = new VeiculoUC();
        jComboBox3.
                setModel(new DefaultComboBoxModel(vuc.buscarVeiculo().toArray()));
        
        FuncionarioUC fuc = new FuncionarioUC();
        jComboBox1.
                setModel(new DefaultComboBoxModel(fuc.buscarFuncionario().toArray()));
        
        ClienteUC cuc = new ClienteUC();
        jComboBox2.
                setModel(new DefaultComboBoxModel(cuc.buscarCliente().toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();

        jLabel1.setText("Breve Descrição sobre o Atendimento");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("Valor");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Funcionário");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Cliente");

        jLabel5.setText("Veículo");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private Atendimento atendimento;
    @Override
    public void setDados(EntidadesVirtuais ev) {
       atendimento = (Atendimento) ev;
       jTextArea1.setText(atendimento.getDescricao());
       jTextField1.setText(atendimento.getValor()); 
    }
       @Override
    public EntidadesVirtuais getDados() {
        if(atendimento==null)
            atendimento =new Atendimento();
        atendimento.setDescricao(jTextArea1.getText());
        atendimento.setValor(jTextField1.getText());
        atendimento.setVeiculos((Veiculo) jComboBox3.getSelectedItem());
        atendimento.setClientes((Cliente) jComboBox2.getSelectedItem());
        atendimento.setFuncionarios((Funcionario) jComboBox1.getSelectedItem());
        return atendimento;  
    }

/*return new AtendimentoBuild((jTextArea1.getText(),jTextField1.getText(),
        ((Cliente) jComboBox2.getSelectedItem()),
                (Funcionario) jComboBox1.getSelectedItem()),
                        (Veiculo) jComboBox3.getSelectedItem(), null).build();
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Atendimento Inválido");
        }
        return null;*/

/*Atendimento ab = new AtendimentoBuild(jTextArea1.getText(), jTextField1.getText(), (Cliente) jComboBox2.getSelectedItem(),
        (Funcionario) jComboBox1.getSelectedItem(), (Veiculo) jComboBox3.getSelectedItem(), null).build();
UC.salvar(ab);

/*return new AtendimentoBuild(jTextArea1.getText(),
        jTextField1.getText(), ((Cliente) jComboBox2.getSelectedItem()),
        ((Funcionario) jComboBox1.getSelectedItem()), ((Veiculo) jComboBox3.getSelectedItem()), null).build();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Atendimento Inválido");
        }
        return null;
    }   catch (Exception ex) {
            Logger.getLogger(PainelCadastroAtendimento.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;*/
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
