/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mecanica;

import com.mycompany.cadastros.PainelCadastroCargo;
import com.mycompany.cadastros.PainelCadastroFuncionario;
import com.mycompany.cadastros.PainelCadastroCliente;
import com.mycompany.cadastros.PainelCadastroCidade;
import com.mycompany.cadastros.PainelCadastroEstado;
import com.mycompany.cadastros.PainelCadastroProduto;
import com.mycompany.cadastros.PainelCadastroAtendimento;
import com.mycompany.cadastros.PainelCadastroEndereco;
import com.mycompany.cadastros.PainelCadastroUsuario;
import com.mycompany.cadastros.PainelCadastroVeiculo;
import com.mycompany.models.Atendimento;
import com.mycompany.models.Cargo;
import com.mycompany.models.Cidade;
import com.mycompany.models.Cliente;
import com.mycompany.models.Endereco;
import com.mycompany.models.Estado;
import com.mycompany.models.Funcionario;
import com.mycompany.models.Produto;
import com.mycompany.models.Usuario;
import com.mycompany.models.Veiculo;
import com.mycompany.util.Util;

import javax.swing.JOptionPane;

/**
 *
 * @author matheus ribeiro
 * @author danilo silva
 */
public class Principal extends javax.swing.JFrame {
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        setTitle("MY-GARAGE");
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Atendimento = new javax.swing.JMenuItem();
        Cargo = new javax.swing.JMenuItem();
        Cidade = new javax.swing.JMenuItem();
        Cliente = new javax.swing.JMenuItem();
        Endereco = new javax.swing.JMenuItem();
        Estado = new javax.swing.JMenuItem();
        Funcionario = new javax.swing.JMenuItem();
        Produto = new javax.swing.JMenuItem();
        Usuario = new javax.swing.JMenuItem();
        Veiculo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ListagemAtendimento = new javax.swing.JMenuItem();
        ListagemCargo = new javax.swing.JMenuItem();
        ListagemCidade = new javax.swing.JMenuItem();
        ListagemCliente = new javax.swing.JMenuItem();
        ListagemEndereco = new javax.swing.JMenuItem();
        ListagemEstado = new javax.swing.JMenuItem();
        ListagemFuncionario = new javax.swing.JMenuItem();
        ListagemProduto = new javax.swing.JMenuItem();
        ListagemUsuario = new javax.swing.JMenuItem();
        ListagemVeiculo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        DicaCadastroFuncionario = new javax.swing.JMenuItem();
        DicaCadastroCliente = new javax.swing.JMenuItem();
        DicaCadastroEndereco = new javax.swing.JMenuItem();
        DicaCadastroAtendimento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(4);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/sair.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton2.setBackground(new java.awt.Color(0, 102, 204));
        jButton2.setText("Desenvolvido por: Matheus Ribeiro Sant'Ana e Danilo Silva de Lima");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/garagem.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jMenu1.setBorder(null);
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/cadastro.png"))); // NOI18N
        jMenu1.setText("Cadastros");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Atendimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/exame.png"))); // NOI18N
        Atendimento.setText("Atendimento");
        Atendimento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Atendimento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Atendimento.setFocusPainted(true);
        Atendimento.setFocusable(true);
        Atendimento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Atendimento.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Atendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtendimentoActionPerformed(evt);
            }
        });
        jMenu1.add(Atendimento);

        Cargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/funcao.png"))); // NOI18N
        Cargo.setText("Cargo");
        Cargo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Cargo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cargo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Cargo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargoActionPerformed(evt);
            }
        });
        jMenu1.add(Cargo);

        Cidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/cidade.png"))); // NOI18N
        Cidade.setText("Cidade");
        Cidade.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Cidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cidade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Cidade.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CidadeActionPerformed(evt);
            }
        });
        jMenu1.add(Cidade);

        Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/clientes.png"))); // NOI18N
        Cliente.setText("Cliente");
        Cliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Cliente.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });
        jMenu1.add(Cliente);

        Endereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/endereco-residencial.png"))); // NOI18N
        Endereco.setText("Endereço");
        Endereco.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Endereco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Endereco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Endereco.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnderecoActionPerformed(evt);
            }
        });
        jMenu1.add(Endereco);

        Estado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/governo.png"))); // NOI18N
        Estado.setText("Estado");
        Estado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Estado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Estado.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoActionPerformed(evt);
            }
        });
        jMenu1.add(Estado);

        Funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/carteira-de-identidade.png"))); // NOI18N
        Funcionario.setText("Funcionário");
        Funcionario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Funcionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Funcionario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Funcionario.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(Funcionario);

        Produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/ipq.png"))); // NOI18N
        Produto.setText("Produto");
        Produto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Produto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Produto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Produto.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(Produto);

        Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/adicionar-usuario.png"))); // NOI18N
        Usuario.setText("Usuário");
        Usuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Usuario.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(Usuario);

        Veiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/assinando.png"))); // NOI18N
        Veiculo.setText("Veículo");
        Veiculo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Veiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Veiculo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Veiculo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Veiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VeiculoActionPerformed(evt);
            }
        });
        jMenu1.add(Veiculo);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/listagem.png"))); // NOI18N
        jMenu2.setText("Listagens");

        ListagemAtendimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/exame.png"))); // NOI18N
        ListagemAtendimento.setText("Atendimento");
        ListagemAtendimento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ListagemAtendimento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListagemAtendimento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ListagemAtendimento.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ListagemAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListagemAtendimentoActionPerformed(evt);
            }
        });
        jMenu2.add(ListagemAtendimento);

        ListagemCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/funcao.png"))); // NOI18N
        ListagemCargo.setText("Cargo");
        ListagemCargo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ListagemCargo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListagemCargo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ListagemCargo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ListagemCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListagemCargoActionPerformed(evt);
            }
        });
        jMenu2.add(ListagemCargo);

        ListagemCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/cidade.png"))); // NOI18N
        ListagemCidade.setText("Cidade");
        ListagemCidade.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ListagemCidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListagemCidade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ListagemCidade.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ListagemCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListagemCidadeActionPerformed(evt);
            }
        });
        jMenu2.add(ListagemCidade);

        ListagemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/clientes.png"))); // NOI18N
        ListagemCliente.setText("Cliente");
        ListagemCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ListagemCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListagemCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ListagemCliente.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ListagemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListagemClienteActionPerformed(evt);
            }
        });
        jMenu2.add(ListagemCliente);

        ListagemEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/endereco-residencial.png"))); // NOI18N
        ListagemEndereco.setText("Endereço");
        ListagemEndereco.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ListagemEndereco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListagemEndereco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ListagemEndereco.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ListagemEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListagemEnderecoActionPerformed(evt);
            }
        });
        jMenu2.add(ListagemEndereco);

        ListagemEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/governo.png"))); // NOI18N
        ListagemEstado.setText("Estado");
        ListagemEstado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ListagemEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListagemEstado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ListagemEstado.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ListagemEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListagemEstadoActionPerformed(evt);
            }
        });
        jMenu2.add(ListagemEstado);

        ListagemFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/carteira-de-identidade.png"))); // NOI18N
        ListagemFuncionario.setText("Funcionário");
        ListagemFuncionario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ListagemFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListagemFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ListagemFuncionario.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ListagemFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListagemFuncionarioActionPerformed(evt);
            }
        });
        jMenu2.add(ListagemFuncionario);

        ListagemProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/ipq.png"))); // NOI18N
        ListagemProduto.setText("Produto");
        ListagemProduto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ListagemProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListagemProduto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ListagemProduto.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ListagemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListagemProdutoActionPerformed(evt);
            }
        });
        jMenu2.add(ListagemProduto);

        ListagemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/do-utilizador.png"))); // NOI18N
        ListagemUsuario.setText("Usuário");
        ListagemUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ListagemUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListagemUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ListagemUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ListagemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListagemUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(ListagemUsuario);

        ListagemVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/prancheta.png"))); // NOI18N
        ListagemVeiculo.setText("Veículo");
        ListagemVeiculo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ListagemVeiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListagemVeiculo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ListagemVeiculo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ListagemVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListagemVeiculoActionPerformed(evt);
            }
        });
        jMenu2.add(ListagemVeiculo);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/ideia.png"))); // NOI18N
        jMenu3.setText("Dicas");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        DicaCadastroFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/duvida.png"))); // NOI18N
        DicaCadastroFuncionario.setText("Como Cadastrar Funcionário");
        DicaCadastroFuncionario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DicaCadastroFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DicaCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DicaCadastroFuncionarioActionPerformed(evt);
            }
        });
        jMenu3.add(DicaCadastroFuncionario);

        DicaCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/duvida.png"))); // NOI18N
        DicaCadastroCliente.setText("Como Cadastrar Cliente");
        DicaCadastroCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DicaCadastroCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DicaCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DicaCadastroClienteActionPerformed(evt);
            }
        });
        jMenu3.add(DicaCadastroCliente);

        DicaCadastroEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/duvida.png"))); // NOI18N
        DicaCadastroEndereco.setText("Como Cadastrar Endereço");
        DicaCadastroEndereco.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DicaCadastroEndereco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DicaCadastroEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DicaCadastroEnderecoActionPerformed(evt);
            }
        });
        jMenu3.add(DicaCadastroEndereco);

        DicaCadastroAtendimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/duvida.png"))); // NOI18N
        DicaCadastroAtendimento.setText("Como Cadastrar Atendimento");
        DicaCadastroAtendimento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DicaCadastroAtendimento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DicaCadastroAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DicaCadastroAtendimentoActionPerformed(evt);
            }
        });
        jMenu3.add(DicaCadastroAtendimento);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null, "E-mails para contato\nMatheus - 802.243@alunos.unigran.br\nDanilo - 802.245@alunos.unigran.br");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CidadeActionPerformed
        new Cadastro(this, true, new PainelCadastroCidade()).setVisible(true);
    }//GEN-LAST:event_CidadeActionPerformed

    private void AtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtendimentoActionPerformed
        new Cadastro(this, true, new PainelCadastroAtendimento()).setVisible(true);
    }//GEN-LAST:event_AtendimentoActionPerformed

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        new Cadastro(this, true, new PainelCadastroCliente()).setVisible(true);
    }//GEN-LAST:event_ClienteActionPerformed

    private void CargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargoActionPerformed
        new Cadastro(this, true, new PainelCadastroCargo()).setVisible(true);
    }//GEN-LAST:event_CargoActionPerformed

    private void EnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnderecoActionPerformed
        new Cadastro(this, true, new PainelCadastroEndereco()).setVisible(true);
    }//GEN-LAST:event_EnderecoActionPerformed

    private void EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoActionPerformed
        new Cadastro(this, true, new PainelCadastroEstado()).setVisible(true);
    }//GEN-LAST:event_EstadoActionPerformed

    private void FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncionarioActionPerformed
       new Cadastro(this, true, new PainelCadastroFuncionario()).setVisible(true);
    }//GEN-LAST:event_FuncionarioActionPerformed

    private void ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutoActionPerformed
        new Cadastro(this, true, new PainelCadastroProduto()).setVisible(true);
    }//GEN-LAST:event_ProdutoActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        new Cadastro(this, true, new PainelCadastroUsuario()).setVisible(true);
    }//GEN-LAST:event_UsuarioActionPerformed

    private void VeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VeiculoActionPerformed
       new Cadastro(this, true, new PainelCadastroVeiculo()).setVisible(true);
    }//GEN-LAST:event_VeiculoActionPerformed

    private void ListagemAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListagemAtendimentoActionPerformed
        new Listagem(this, false,Atendimento.class,new PainelCadastroAtendimento()).setVisible(true);
    }//GEN-LAST:event_ListagemAtendimentoActionPerformed

    private void ListagemCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListagemCargoActionPerformed
        new Listagem(this, false,Cargo.class,new PainelCadastroCargo()).setVisible(true);
    }//GEN-LAST:event_ListagemCargoActionPerformed

    private void ListagemCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListagemCidadeActionPerformed
        new Listagem(this, false,Cidade.class,new PainelCadastroCidade()).setVisible(true);
    }//GEN-LAST:event_ListagemCidadeActionPerformed

    private void ListagemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListagemClienteActionPerformed
        new Listagem(this, false,Cliente.class,new PainelCadastroCliente()).setVisible(true);
    }//GEN-LAST:event_ListagemClienteActionPerformed

    private void ListagemEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListagemEnderecoActionPerformed
        new Listagem(this, false,Endereco.class,new PainelCadastroEndereco()).setVisible(true);
    }//GEN-LAST:event_ListagemEnderecoActionPerformed

    private void ListagemEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListagemEstadoActionPerformed
        new Listagem(this, false,Estado.class,new PainelCadastroEstado()).setVisible(true);
    }//GEN-LAST:event_ListagemEstadoActionPerformed

    private void ListagemFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListagemFuncionarioActionPerformed
        new Listagem(this, false,Funcionario.class,new PainelCadastroFuncionario()).setVisible(true);
    }//GEN-LAST:event_ListagemFuncionarioActionPerformed

    private void ListagemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListagemProdutoActionPerformed
        new Listagem(this, false,Produto.class,new PainelCadastroProduto()).setVisible(true);
    }//GEN-LAST:event_ListagemProdutoActionPerformed

    private void ListagemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListagemUsuarioActionPerformed
        new Listagem(this, false,Usuario.class,new PainelCadastroUsuario()).setVisible(true);
    }//GEN-LAST:event_ListagemUsuarioActionPerformed

    private void ListagemVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListagemVeiculoActionPerformed
        new Listagem(this, false,Veiculo.class,new PainelCadastroVeiculo()).setVisible(true);
    }//GEN-LAST:event_ListagemVeiculoActionPerformed

    private void DicaCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DicaCadastroFuncionarioActionPerformed
        JOptionPane.showMessageDialog(null, "Para cadastrar um novo funcionário é preciso: \n\n"
                + "*Ter cadastrado um endereço no nome do funcionário\n"
                + "*Ter cadastrado o cargo que o funcionário terá"
                + "\n\nPara saber como cadastrar um endereço vá até\n"
                + "Dicas>Como Cadastrar Endereço");
    }//GEN-LAST:event_DicaCadastroFuncionarioActionPerformed

    private void DicaCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DicaCadastroClienteActionPerformed
        JOptionPane.showMessageDialog(null, "Para cadastrar um novo cliente é preciso: \n\n"
                + "*Ter cadastrado um endereço no nome do cliente\n"
                + "\n\nPara saber como cadastrar um endereço vá até\n"
                + "Dicas>Como Cadastrar Endereço");
    }//GEN-LAST:event_DicaCadastroClienteActionPerformed

    private void DicaCadastroEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DicaCadastroEnderecoActionPerformed
        JOptionPane.showMessageDialog(null, "Para cadastrar um novo endereço é preciso: \n\n"
                + "*Ter cadastrado o primeiramente o estado do endereço\n"
                + "*Ter cadastrado após o estado, a cidade do endereço\n"
                + "Cadastros>Estado"
                + "\nCadastro>Cidade\n"
                + "Cadastro>Endereço");
    }//GEN-LAST:event_DicaCadastroEnderecoActionPerformed

    private void DicaCadastroAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DicaCadastroAtendimentoActionPerformed
        JOptionPane.showMessageDialog(null, "Para cadastrar um novo atendimento é preciso: \n\n"
                + "*Ter cadastrado o veículo que será atendido\n"
                + "*Ter cadastrado o cliente que será atendido\n"
                + "*Ter cadastrado o funcionário que irá atender\n"
                + "Cadastros>Veículo"
                + "\nCadastro>Cliente\n"
                + "Cadastro>Funcionário"
                + "\nCadastro>Atendimento");
    }//GEN-LAST:event_DicaCadastroAtendimentoActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Atendimento;
    private javax.swing.JMenuItem Cargo;
    private javax.swing.JMenuItem Cidade;
    private javax.swing.JMenuItem Cliente;
    private javax.swing.JMenuItem DicaCadastroAtendimento;
    private javax.swing.JMenuItem DicaCadastroCliente;
    private javax.swing.JMenuItem DicaCadastroEndereco;
    private javax.swing.JMenuItem DicaCadastroFuncionario;
    private javax.swing.JMenuItem Endereco;
    private javax.swing.JMenuItem Estado;
    private javax.swing.JMenuItem Funcionario;
    private javax.swing.JMenuItem ListagemAtendimento;
    private javax.swing.JMenuItem ListagemCargo;
    private javax.swing.JMenuItem ListagemCidade;
    private javax.swing.JMenuItem ListagemCliente;
    private javax.swing.JMenuItem ListagemEndereco;
    private javax.swing.JMenuItem ListagemEstado;
    private javax.swing.JMenuItem ListagemFuncionario;
    private javax.swing.JMenuItem ListagemProduto;
    private javax.swing.JMenuItem ListagemUsuario;
    private javax.swing.JMenuItem ListagemVeiculo;
    private javax.swing.JMenuItem Produto;
    private javax.swing.JMenuItem Usuario;
    private javax.swing.JMenuItem Veiculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

}
